### ISSUE TITLE
Untrappable Kinesis Producer Library (KPL) (Java) Errors from child process

### ISSUE THREAD

**Issue by martin-walsh** [awslabs/amazon-kinesis-producer#103]
When using KPL (version 0.12.3) we have encountered the following error scenario and have been unable to handle the condition.

Setup / Initial State:
KPL application running and working, all IAM policies set up and correct.  At this state, all should be well.

Action:
Change of IAM role that removes grants to access Kinesis stream.

Result:
KPL application begins to log errors from child process, but the error is not communicated properly to the parent Java process.  i.e. no thrown exceptions, Futures don't fail...

Is there a way to trap this error, as otherwise publishes are effectively skipped?

Please see attached log example & groovy code snippet.
[snippet-groovy.txt](https://github.com/awslabs/amazon-kinesis-producer/files/1002992/snippet-groovy.txt)
[kpl-log-example.txt](https://github.com/awslabs/amazon-kinesis-producer/files/1002993/kpl-log-example.txt)

**Comment by pfifer** [comment]
Thanks for reporting this.  We will investigate further.

**Comment by martin-walsh** [comment]
Guys,

I can't reproduce this anymore & we tried doing it in prod again.  I think I might have raised a red herring.

**Comment by pfifer** [comment]
Thanks for following up.  I'm going to close this for now.  Feel free to reopen this if it reoccurs.
