### ISSUE TITLE
After get WriteProvisionedThroughputExceeded for a while, native process get cpu 100%

### ISSUE THREAD

**Issue by humbledude** [awslabs/amazon-kinesis-producer#122]
I'm using 0.12.5 and had load test with KPL.
Kinesis stream had 1 shard, and load was 2000 TPS with 1kB record for 5 minutes.

My producer config was :
```
    .setRequestTimeout(60_000)
    .setRecordMaxBufferedTime(100)
    .setRecordTtl(600_000);
```

I expected kinesis would get `WriteProvisionedThroughputExceeded` for 5 minutes,
and it would recovered in 10 minutes, because of `RecordTtl(10minutes)`.

But it didn't recover for 20 minutes, and `top` said kinesis native process was still working.
`11562 ubuntu    20   0  875876 305384   7936 R 99.3 14.9  28:47.80 kinesis_p+`
I had to kill the java app.
I could reproduce the issue whenever do load test like this.

I think there could be bug in retry & record ttl.
but I didn't get any log from it.
Could you figure it out?
I should use AWS SDK instead of KPL until then...

**Comment by pfifer** [comment]
The KPL doesn't currently provide any back pressure, but will keep retrying for the entire record TTL.  This means that the KPL will keep retrying the record for 10 minutes.  When additional records are added it adds further pressure, and increases the throttling rate.  
The best option is to have your publishing application have a limit of how many records can be inflight, and when that limit is reached the producer should block or divert records.

**Comment by humbledude** [comment]
What I thought the bug was..
1. it seemed to be trying putRecords than I expected.
(expected = 10mins, actual = over 20mins)

2. it worked too hard.
(cpu 100% for retry)

Anyway, I used queue for buffering for my application,
which works with some delay between each putRecords operations,
and that reduced cpu usage.
You could add some option to KPL for this situation.

Thank you.
