### ISSUE TITLE
Does KPL ensure that a record is put into a stream only if the previous calls to addUserRecord have completed successfully?

### ISSUE THREAD

**Issue by behrangsa** [awslabs/amazon-kinesis-producer#128]
As `addUserRecord` is async, what would happen if there are 2 calls to `addUserRecord` but:

* The first call fails (even after all the retries)
* The second call succeeds

From what I can see, KPL's async nature could cause data loss and it is not suitable for scenarios that require at-least-once delivery. Or am I missing something here?

**Comment by pfifer** [comment]
The short answer is no.  

Breaking a part your question
> From what I can see, KPL's async nature could cause data loss...

There is no data loss in this case, as the application is given the option of retrying any failed records.  Data loss will only occur if the application doesn't retry the records. 

> ...scenarios that require at-least-once delivery...

As Kinesis is a distributed system, it cannot guarantee at lease once delivery.  When a put operation fails with a 500 response you can't be know whether Kinesis was able to store the records, or not.  This means on a 500 response you __must__ retry sending the records to ensure durability.  The KPL does part of that for you via the default set of retries.  On the consumer side you would need to provide some degree of duplicate handling.

> As `addUserRecord` is async, what would happen if there are 2 calls to `addUserRecord` but:
> * The first call fails (even after all the retries)
> * The second call succeeds

Each user record is independent from every other user record.  They can succeed, and fail on their own.  During aggregation user records maybe combined to be sent to Kinesis, but should they fail they may aggregate in a different way on the next attempt.

If you want to ensure that one record will only show after a previous record you must only attempt to send the second record once you've verified the success of the first record.

In addition to this the KPL publishes to a stream, and not a specific shard.  If two user records are destined for different shards they will never be aggregated together.  Kinesis cannot guarantee ordering of records when the records are held by different shards.  As I said above the only way to guarantee ordering is to wait until the first record has been received by Kinesis before attempting to send the next record to Kinesis.

**Comment by behrangsa** [comment]
Thanks for the reply.

> There is no data loss in this case, as the application is given the option of retrying any failed records. Data loss will only occur if the application doesn't retry the records.

You are right. While the application will be notified that a put operation has failed to avoid data loss, it is possible for a shard on a stream to end up with gaps: if we pretend records 1, 2, and 3 all have partition keys that puts them inside the same shard, if 1 and 3 succeed but 2 fails, as KPL is async, the shard will end up with records 1 and 3.

> As Kinesis is a distributed system, it cannot guarantee at lease once delivery. When a put operation fails with a 500 response you can't be know whether Kinesis was able to store the records, or not. This means on a 500 response you must retry sending the records to ensure durability. The KPL does part of that for you via the default set of retries. On the consumer side you would need to provide some degree of duplicate handling.

I meant at-least-once, not exactly-once.

> If you want to ensure that one record will only show after a previous record you must only attempt to send the second record once you've verified the success of the first record.

Yes. I am building a sink Kafka connector to export data from a Kafka topic into a Kinesis stream and need to preserve partition-level ordering. I can implement the logic to ensure records from a given partition will be sent to the same shard but I also need to ensure ordering correct, hence I think the async-nature of KPL is not helpful for my use case.

Thanks for the clarifications. :)
