### ISSUE TITLE
Failed to parse configuration at: kinesis.region; region must match the pattern ^([a-z]+-[a-z]+-[0-9])?$, got us-gov-west-1

### ISSUE THREAD

**Issue by JTarasovic** [awslabs/amazon-kinesis-producer#146]
Trying to use the KPL to publish to a stream in govcloud. It fails to start with this error.

`Failed to parse configuration at: kinesis.region; region must match the pattern ^([a-z]+-[a-z]+-[0-9])?$, got us-gov-west-1`

Is this intentional or am I doing something wrong? Is there really nobody using KPL in govcloud? Doesn't the SDK have methods for validating regions that doesn't involve using a regex?

I'd be happy to submit a PR if this isn't the correct behavior but we're trying to deploy this application to our production environment so if there's a way to circumvent this, we'd love to hear it.

Thanks.

**Comment by pfifer** [comment]
It's somewhat of a legacy check, and is no longer needed.  I do intend to remove some of the other checks as well, as they don't provide any value.

**Comment by JTarasovic** [comment]
I'm using a reflection hack to set it for now but I'd be willing to help if that'd be helpful.

**Comment by JTarasovic** [comment]
Actually, the reflection hack doesn't work since the region is also checked in C++.

https://github.com/awslabs/amazon-kinesis-producer/blob/master/aws/kinesis/core/configuration.h#L898

**Comment by JTarasovic** [comment]
I see that the build instructions are out of date ( #67 ). Would it be possible to get an abbreviated rundown so that we can compile the binaries with a better check? I'd really appreciate it as this is keeping our application from going live.

**Comment by arun9486** [comment]
@JTarasovic  were you able to make this work for govcloud?

**Comment by JTarasovic** [comment]
Not really. I tried altering both the Java and C++ components but I wasn't able to get the C++ component to build properly because the build instructions are out of date.

I also escalated to our AWS points of contact and no one seems to care.

**Comment by JTarasovic** [comment]
i'm runnin 0.12.10 through our environments tonight. will try w/ us-gov-west-1 tomorrow if everything goes well. specifically 8c3caea0e051308

**Comment by rodgjame** [comment]
I just hit this issue for the same reason. Has there been any movement on it?

**Comment by JTarasovic** [comment]
We haven't had any issues since we upgraded to 0.12.10. The checks on master for java and c++ both look good.

**Comment by JTarasovic** [comment]
This has been fixed, at least for my use case, for going on a year so I'm going to close.

thank you!
