### ISSUE TITLE
Native KPL process idle CPU consumption

### ISSUE THREAD

**Issue by kevincdeng** [awslabs/amazon-kinesis-producer#15]
The KPL native process consumes a significant amount of CPU (10-20% of one core) while idle. This should be reduced.

**Comment by xujiaxj** [comment]
Thanks for opening this. Hope there is a good solution soon.

**Comment by vmendi** [comment]
We also noticed this.

**Comment by kevincdeng** [comment]
Release 0.10.1 is now available and should address this issue.

**Comment by xujiaxj** [comment]
Thx. It works good for me.
