### ISSUE TITLE
KinesisProducer.destroy() doesn't kill the child process

### ISSUE THREAD

**Issue by vmendi** [awslabs/amazon-kinesis-producer#16]
kinesis_produce is still there and consuming ~15% of CPU.

**Comment by kevincdeng** [comment]
Hi vmendi,

Which OS is this on? Are you using v0.10.0?

**Comment by vmendi** [comment]
OSX 10.9.5, KPL 0.10.0.

Thanks Kevin.

**Comment by kevincdeng** [comment]
This is most likely the same issue as [14](https://github.com/awslabs/amazon-kinesis-producer/issues/14).

**Comment by kevincdeng** [comment]
Release 0.10.1 is now available and should address this issue.
