### ISSUE TITLE
Upgrade dependency on AWS SDK

### ISSUE THREAD

**Issue by behrangs-sportsbet** [awslabs/amazon-kinesis-producer#164]
At the moment KPL depends on AWS SDK `1.11.128` which is about 7 months old.

The current SDK version is [1.11.244](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core/1.11.244).

An updated version of KPL would allow us to use the latest SDK alongside KPL.

**Comment by pfifer** [comment]
0.12.8 now has the upgraded AWS SDK.

Feel free to reopen if you have more questions or issues.
