### ISSUE TITLE
Question on node.js lambda

### ISSUE THREAD

**Issue by sthurber** [awslabs/amazon-kinesis-producer#176]
Just a question in the interest of not making assumptions. We have node.js lambdas that write to a kinesis stream using the following...https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Kinesis.html.

Does the required update to the KPL for 2/9/18 effect this code in any way?

Thanks!

**Comment by pfifer** [comment]
The update for the KPL has no affect on other uses of the AWS SDKs.  The update requirement is due the the KPL using bundled certificates, and missing many common root certificates.

In general if you're using the AWS provided SDKs on recent operating systems you should be fine.  

Feel free to reopen the issue if you have any further questions.

**Comment by sthurber** [comment]
Thanks!
