### ISSUE TITLE
Change License into a standard open source license (Apache?)

### ISSUE THREAD

**Issue by iemejia** [awslabs/amazon-kinesis-producer#180]
KPL is licensed with the Amazon Software License and this is in the gray area for multiple Apache based projects. For example Apache Flink cannot provide binary artifacts of its Kinesis connector because of this limitation. Any chance this can be relicensed into an Apache friendly license.
https://www.apache.org/legal/resolved.html#category-x

**Comment by aromanenko-dev** [comment]
Any updates on this topic? Are there any plans to change a license from ASL to Apache-compatible?

**Comment by iemejia** [comment]
This was done via #256 so closing. Good to see this happening.
