### ISSUE TITLE
Use KPL with a Kinesis Endpoint and no Kinesis Port

### ISSUE THREAD

**Issue by benderTheCrime** [awslabs/amazon-kinesis-producer#184]
The KPL throws an error if the KinesisProducerConfiguration class is called without a KinesisPort. It expects a long between 1-65k. 

Is there a way to unset the Port or pass a fully-qualified Kinesis URL to call? 

If no KinesisPort option is provided at all, it sets it to the default, 443.

**Comment by pfifer** [comment]
I'm not sure I understand what you're trying to do.  Do you intend to unset the port number, or want it to default to 443?

**Comment by benderTheCrime** [comment]
I want to unset the port number.

**Comment by pfifer** [comment]
The endpoint configuration is passed to a native C++ application that will eventually use it to connect to Kinesis via the AWS C++ SDK via `connect(...)`.  443 is the well known port number for HTTP over TLS (HTTPS), which is the reason for the default value.  As Kinesis isn't available over HTTP when no port number is specified the AWS C++ SDK will default to port 443.  So even if you were to not specify the port number it would still default to 443. 

It's possible to use HTTPS over ports other than 443, the port number override allows for that case.  This is used for some of the testing. 

This sort of sounds like conditional setting.  Is the goal to have the KPL ignore property statements that are `<name>=`?

**Comment by benderTheCrime** [comment]
No, the goal is to mitigate different VPCes across different environments. The DNS for the VPCes out of the box is going to be different across many different accounts, etc. So, to combat this, I'm doing one of two things:

- In a container running consul, aliasing the VPCe to "kinesis." This can be hit via the aws-cli from the host and from the container running the KPL (Maxwell) provided I use "--no-verify-ssl"
- Using a DNS record for "kinesis" that points to the VPCe. This is also possible to use from the CLI from any host in the VPC.

Unfortunately, in the former case, if the endpoint resolves to "kinesis:443" this does not seem to work, I get a lot of curl errors:

```
19:24:37,633 ERROR LogInputStreamReader - [2018-02-20 19:24:37.633337] [0x00000044][0x00007f45823ee700] [error] [AWS Log: ERROR](CurlHttpClient)Curl returned error code 7
```

I'm setting `VerifyCertificate = false`, `KinesisEndpoint = kinesis`, and I'm unsetting the port.

**Comment by pfifer** [comment]
Curl error code indicates that the Curl couldn't connect to the host.  It appears the endpoint resolved correctly, otherwise it Curl would fail with error code 6.  The port number is stripped before the name is sent to the resolver.  The error that would cause 7 would most likely be the endpoint isn't responding to the SYN packets. In the testing I've done this only shows up if the security group doesn't allow inbound 443 for the VPC hosts.

**Comment by benderTheCrime** [comment]
The security group is currently configured to allow all incoming/outgoing traffic for 0.0.0.0/0.

In any case I'm closing this. I found a workaround:

Just use the cli to grab the VPCe's before Maxwell starts and inject the non-default VPCe DNS name into KPL configuration.

Thanks.
