### ISSUE TITLE
Upgrade Java SDK to > 1.11.272

### ISSUE THREAD

**Issue by markglh** [awslabs/amazon-kinesis-producer#192]
KPL AWS Java SDK = 1.11.245
KCL AWS Java SDK = 1.11.272, and requires a minimum of 1.11.272. 

This is likely going to cause a lot of people problems if both consuming and producing in the same application.

**Comment by dy10** [comment]
+1
I was trying latest version of AWS JAVA SDK for SQS and it threw error because Core is old due to KPL. It worked fine when i downgraded SQS version, but now i cant use latest features and bug-fixes.

**Comment by dy10** [comment]
In-general we need a frequent release here to be in sync with latest AWS Java SDK Core even if there are no changes to this code. Or remove dependency from SDK core.

**Comment by markglh** [comment]
Seems this is now fixed in the latest release:
https://github.com/awslabs/amazon-kinesis-producer/commit/b0eff40e2c5987f1deadd65cb590b096586ae4cd#diff-9b8a3171d9188976361bb6c1685acd8aL60

**Comment by markglh** [comment]
Though weirdly not in the release notes
