### ISSUE TITLE
Native producer continuously restarts

### ISSUE THREAD

**Issue by derekguist** [awslabs/amazon-kinesis-producer#219]
I'm running the KPL (0.12.9) in an openjdk-based docker image, kernel 4.9.93, glibc 2.24. It won't start up successfully however. The only output is a continual stream, about once per second, of:

>  [kpl-daemon-0000] com.amazonaws.services.kinesis.producer.KinesisProducer: Restarting native producer process.

The same producer seems to start up fine when run outside of docker on my local machine, macOS. I haven't been able to find anything that would suggest what the problem would be and don't know where to look for clues. Is there a fix for this problem?

**Comment by derekguist** [comment]
I figured out what the problem was - it was an issue with my AWS credential provider not working in the docker container, nothing inherent with the producer itself. However, looking into this I uncovered some strange behavior that was preventing the error from being logged. I'll open a separate issue for that.

**Comment by derekguist** [comment]
Opened #221 for the aforementioned issue that prevented exception logging.

**Comment by bsmithEG** [comment]
Is there a configurable way to prevent the native producer process from constantly trying to restart?   An example would be when using the STS credentials provider and credentials become invalidated at runtime.  I haven't exactly figured out a way to prevent the kinesisproducer to constantly leak RTE's trying to restart.
