### ISSUE TITLE
KinesisProducer is not correctly destroying callbackCompletionExecutor

### ISSUE THREAD

**Issue by xbcratos** [awslabs/amazon-kinesis-producer#224]
When destroying KinesisProducer instances, destroy method is not shutting down callbackCompletionExecutor. This makes Daemon child object to still be alive occupying 8MB of heap memory each one.

Creating and destroying lots of KinesisProducer instances will result in a Heap Out Of Memory exception.

**Comment by ankugar** [comment]
The fix was merged with this commit: https://github.com/xbcratos/amazon-kinesis-producer/commit/e153a09d5829b75fdb2583dd07db1f55d805007e.

Thank you for the fix.
