### ISSUE TITLE
bootstrap.sh Could not resolve host: d3mddf4lzrx5uw.cloudfront.net

### ISSUE THREAD

**Issue by oboudry** [awslabs/amazon-kinesis-producer#233]
The URL for the libraries used in bootstrap.sh is not resolving

`+ curl -L http://d3mddf4lzrx5uw.cloudfront.net/openssl-1.0.1m.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: d3mddf4lzrx5uw.cloudfront.net
`

**Comment by tredston** [comment]
See 206.

**Comment by oboudry** [comment]
Duplicate of #206
