### ISSUE TITLE
DataTypeConverter Failure 

### ISSUE THREAD

**Issue by Joseph2424** [awslabs/amazon-kinesis-producer#242]
Failing to run my Java Application referencing v.0.12.11 on a windows 10 machine.  It's failing at this line of code:

String digestHex = DatatypeConverter.printHexBinary(digest);

NoClassDefFoundError:
detailMessage: "javax/xml/bind/DatatypeConverter"

**Comment by Joseph2424** [comment]
Never mind.  Adding the following dependency resolved the issue.

<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>

**Comment by leonardiwagner** [comment]
I had the same issue using jdk 11 and library version 0.14.0 (latest) on linux. [It seems to be related to the jdk version we're using](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j). 

Thanks for the solution, it works for me as well.
