### ISSUE TITLE
Unable to read KPL produced records (filled with illegal characters) using non-KCL consumer

### ISSUE THREAD

**Issue by ssgao** [awslabs/amazon-kinesis-producer#245]
We have a setup that uses KPL to produce record and lambda (`aws-sdk-go`-based) to consumes it. I am able to reproduce it using the KPL Java Sample Application (https://github.com/awslabs/amazon-kinesis-producer/tree/master/java/amazon-kinesis-producer-sample) using steps as follow:

1. create a 1-shard kinesis stream. That's it, no encryption, etc.
2. Start KPL sample application and have it pointed to that kinesis stream.
3. tail kinesis events using https://github.com/quiver/sisenik ```sisenik --stream-name {stream-name-here} --limit 10000 --interval 1```

KPL sample app produces 10k lines in 5 seconds, and you'll see the garbage coming out of kinesis event tailer. This tailer is written in python, but since it's also happening on our lambda using `aws-sdk-go`, I don't think it's an issue on the consumer side.

Everything works fine after we convert the producer to `aws-java-sdk-kinesis`.

**Comment by pgieser** [comment]
It seems likely your consumer does not support de-aggregation (the KPL aggregates records by default I believe, although you can turn this behavior off if you are not interested in efficiency)

https://github.com/awslabs/kinesis-aggregation

**Comment by ssgao** [comment]
Thanks @pgieser, giving that a try now. Will update here.

**Comment by ssgao** [comment]
Closing this ticket as the suggestion works.
