### ISSUE TITLE
Remove slf4j-simple from the deployed artifact

### ISSUE THREAD

**Issue by davidrabinowitz** [awslabs/amazon-kinesis-producer#25]
The maven artifact is deployed with a runtime dependency on slf4j-simple implementation, which may cause a problem in runtime when the user of the library uses another slf4j implementation such as log4j or logback.

Please change the dependency scope of slf4j-simple to "test" in java/amazon-kinesis-producer/pom.xml

**Comment by evnm** [comment]
+1

This issue causes problems when amazon-kinesis-producer is used in conjunction with dropwizard. Specifically, it triggers failure of a workaround for [SLF4J-167](http://jira.qos.ch/browse/SLF4J-167) that is [baked into dropwizard](https://github.com/dropwizard/dropwizard/blob/83edc098bc49ae3168340f6d24324b97c9b500da/dropwizard-logging/src/main/java/io/dropwizard/logging/LoggingUtil.java#L25-L36). Adding an explicit dependency exclusion for slf4j-simple in my project's pom resolved the issue.

**Comment by kevincdeng** [comment]
Fixed in 0.10.2
