### ISSUE TITLE
Question about using protobuf 2.4

### ISSUE THREAD

**Issue by ChengzhiZhao** [awslabs/amazon-kinesis-producer#250]
Hey folks, we have a monolithic application which already has protobuf 2.4 running on production. I tried to add KPL and send data to Kinesis but KPL uses protobuf 2.6

And of course I am getting the following message: 
```Exception in thread "main" java.lang.VerifyError: class com.amazonaws.services.kinesis.producer.protobuf.Messages$PutRecord overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;```

```Exception in thread "kpl-daemon-0000" java.lang.VerifyError: class com.amazonaws.services.kinesis.producer.protobuf.Config$Configuration overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;```

I wonder if anyone has experience with this before. Any suggestion on how to get KPL running with less impact on the monolithic application. Thanks!

**Comment by wsargent** [comment]
The usual way to handle this is to use shading, i.e. move out the classes into a different package so it doesn't conflict with something like https://maven.apache.org/plugins/maven-shade-plugin/.

Disclaimer: I am not an AWS employee or remotely familiar with the internals of KPL.

**Comment by ChengzhiZhao** [comment]
Thanks, @wsargent, we are able to get it shaded jar but includes everything shaded
