### ISSUE TITLE
Missing records while exceeding WriteThoughPut limits

### ISSUE THREAD

**Issue by adarshmthomas** [awslabs/amazon-kinesis-producer#252]
While we continuously exceed write throughput limits over a long period of time, there is a considerable amount of missing records. 
We got the following exception: 
[ERROR] 2019-03-25 16:27:34.568 [kpl-callback-pool-0-thread-0] scribe - Exception during putcom.amazonaws.services.kinesis.producer.UserRecordFailedException
[ERROR] 2019-03-25 16:27:34.568 [kpl-callback-pool-0-thread-0] scribe - Record failed to put - Expired : Record has reached expiration

What can be done to avoid missing records?

**Comment by ChengzhiZhao** [comment]
Hi @adarshmthomas, I think we are in the same boat, I tried to increase TTL but I don't see DLQ in KPL, I was wondering if you figure anything out. Thanks

**Comment by Cory-Bradshaw** [comment]
@adarshmthomas @ChengzhiZhao ,

This sounds like your kinesis stream needs to be scaled up to support your throughput requirements. When the KPL reaches the end of the TTL, the callback registered with the Future of the addUserRecord() calls will be invoked which is your opportunity to take action on this.

If you are constantly hitting throttling, there will be missing data eventually as records start to pile up waiting to be sent out until they inevitably time out.

````
ListenableFuture<UserRecordResult> f =
                kinesis.addUserRecord(STREAM_NAME, partitionKey, data);
        Futures.addCallback(f, new FutureCallback<UserRecordResult>() {
            @Override
            public void onSuccess(UserRecordResult result) {
          
            }

            @Override
            public void onFailure(Throwable t) {
                if (t instanceof UserRecordFailedException) {
                    UserRecordFailedException e = 
                           (UserRecordFailedException) t;
                    UserRecordResult result = e.getResult();

                    String errorList =
                        StringUtils.join(result.getAttempts().stream()
                            .map(a -> String.format(
                                "Delay after prev attempt: %d ms, "
                                        + "Duration: %d ms, Code: %s, "
                                        + "Message: %s",
                                a.getDelay(), a.getDuration(), 
                                a.getErrorCode(),
                                a.getErrorMessage()))
                            .collect(Collectors.toList()), "n");

                    log.error(String.format(
                            "Record failed to put, partitionKey=%s, "
                                    + "payload=%s, attempts:n%s",
                            partitionKey, payload, errorList));
                }
            };
        });
    }

````
