### ISSUE TITLE
KPL doesn't work in ARM architecture

### ISSUE THREAD

**Issue by vijaychd** [awslabs/amazon-kinesis-producer#258]
Anyone faced this issue?

**Comment by matydavid** [comment]
i faced this issue too

**Comment by AGSaidi** [comment]
#334 Adds 64bit Arm support and it's included in 0.14.4.

**Comment by shanmugavel04** [comment]
upgraded the Kinesis producer library to 0.15.11 along with Arm supporting binaries for Graviton to work.
