### ISSUE TITLE
Is there a plan to support compression?

### ISSUE THREAD

**Issue by zmw85** [awslabs/amazon-kinesis-producer#269]
compression like gzip can reduce size significantly, it will be nice if there is a plan to support it as a configurable option.

**Comment by Cory-Bradshaw** [comment]
Thanks for the feature request. When using the KPL, you can provide compressed records to the KPL to have your application manage the compression of the objects. This would also require your consumers of the stream to understand that records will be compressed.

This is not something we are likely to support within the KPL and would be complicated by having the KCL interpret compressed records similar to how it interprets aggregated records. By leaving this up to customer implementation, the right compression algorithms and support for versions of KPL and KCL in use are open for the customer to choose.
