### ISSUE TITLE
Go API Wrapper for KPL

### ISSUE THREAD

**Issue by guygma** [awslabs/amazon-kinesis-producer#270]
Go has native support for wrapping C code (cgo). Has an API wrapper in the same vein as the Java implementation been considered? If not, it is something I would like to encourage. With updated build instructions for the C code and some guidance on the functionality (or documentation) this is something I would have motivation to implement myself. 

What is the feasibility of this proposal?

(A native Go code rewrite of KPL would be even nicer but that doesn't seem as likely...)

**Comment by Cory-Bradshaw** [comment]
@guygma, 

Supporting other languages with the KPL is currently not something we are planning on doing at this time. 

We have recently spent time on fixing up the bootstrap script to make building the native code more trivial.  The current instructions for building these components is to simply run the bootstrap.sh and it should download the required components, build them, then build the C++ components followed by the java components (packed with the C++ binaries).
