### ISSUE TITLE
amazonaws.com.cn not supported on metrics_manager.h

### ISSUE THREAD

**Issue by yangjinfeng-huami** [awslabs/amazon-kinesis-producer#28]
The domain is amazonaws.com.cn  when I use kinesis on China(Beijing) region

The configuration of KPL should be the region "cn-north-1". 
When I only set this region on configuration for KPL, 
 the request will send to 
monitoring.cn-north-1.amazonaws.com and kinesis.cn-north-1.amazonaws.com, while they are not exist.

I found another method config.setCustomEndpoint could resolve this.
But config.setCustomEndpoint for both kinesis and cloudwatch at once. When I set CustomEndpoint 
to kinesis.cn-north-1.amazonaws.com.cn the cloudwatch uploading will not work.

Someone can resolve this issue? Either develop separate endpoints for kinesis and cloudwatch or add new method for the domain setting?
Thanks.

Followings are the  hardcode

 std::chrono::milliseconds upload_frequency = std::chrono::minutes(1),
      std::chrono::milliseconds retry_frequency = std::chrono::seconds(10))
      : executor_(std::move(executor)),
        endpoint_(custom_endpoint.empty()
                      ? "monitoring." + region + ".amazonaws.com"
                      : custom_endpoint),

**Comment by pfifer** [comment]
This should be fixed in the 0.12.1 of the KPL. 

Please re-open if you're still having this issue.

Thanks
