### ISSUE TITLE
Latest version dropped support for windows

### ISSUE THREAD

**Issue by patrickjamesbarry** [awslabs/amazon-kinesis-producer#293]
https://github.com/awslabs/amazon-kinesis-producer/releases

Windows support was completely dropped by this library in latest release, but it is only mentioned as a note.  Why was it dropped???

I still see alot of code in master around Windows.  Will all of the code around windows be removed from this library?

**Comment by Cory-Bradshaw** [comment]
#284 is already open, so I will close this issue to avoid duplicate issues which can dilute +1's from customers impacted.

Please +1 issue #284 so we can prioritize adding support for windows back into the system.
