### ISSUE TITLE
install using maven

### ISSUE THREAD

**Issue by jritsema** [awslabs/amazon-kinesis-producer#295]
Hi. I'm a java newbie and experimenting with this project.  I'm sure this is a dumb question but how would I install this artifact into a new maven project?  I tried adding the dependency into my `pom.xml` and running but it seems to be missing its internal deps (`java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter`).  Do I need to copy all of its deps into my `pom.xml`?  Is there a maven command to do this?  I guess I'm used to this behavior coming from node and go.  Any help is appreciated, thanks!

```xml
<dependency>
  <groupId>com.amazonaws</groupId>
  <artifactId>amazon-kinesis-producer</artifactId>
  <version>0.14.0</version>
</dependency>
```

https://search.maven.org/artifact/com.amazonaws/amazon-kinesis-producer/0.14.0/jar

**Comment by pgieser** [comment]
Sounds like a Java version issue. Make sure you are using Java 8.

**Comment by jritsema** [comment]
update:  I got this to work by adding the following dependencies:

```xml
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>amazon-kinesis-producer</artifactId>
      <version>0.14.0</version>
    </dependency>
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.0</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.25</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jdk14</artifactId>
      <version>1.7.25</version>
    </dependency>
  </dependencies>
```
