### ISSUE TITLE
Doubling throughput by doubling shards

### ISSUE THREAD

**Issue by albehrens** [awslabs/amazon-kinesis-producer#342]
We need to put around 2.500.000 records on our Kinesis stream. Our stream has one shard configured. Putting all records on the stream takes around 15 minutes. This takes too long for us. That is why we added a shard to the stream. We hoped that we were able to transfer all our records in half the time. But that did not happen. Instead it took 15 minutes again.

What can we do to increase throughput?

**Comment by chickensoup** [comment]
Please check your Kafka message key and kinesis producer message partition strategy. By default it will do hash on Kafka message key as Kinesis shard key, so if your messages are having the same key or default null keys, the messages will go into the same shard, the additional shard is not used.

**Comment by albehrens** [comment]
@chickensoup That was it. We were using a hardcoded partition key. We set partition key to random and now throughput is much faster. Thanks.
