### ISSUE TITLE
Can't access cn-north-1 ?

### ISSUE THREAD

**Issue by jameswu0629** [awslabs/amazon-kinesis-producer#36]
Currently doesn't support BJS region ?

[error] [http_client.cc:148] Failed to open connection to kinesis.cn-north-1.amazonaws.com:443 : Host not found (authoritative)

**Comment by benalta** [comment]
Hi, 

Amazon Kinesis Streams supports in BJS region.
You should use this end point: kinesis.cn-north-1.amazonaws.com.cn
If you still have issue, please open a case and you can contact me at benaltar@amazon.com

**Comment by pfifer** [comment]
I've prepared a fix for this in #69

**Comment by pfifer** [comment]
I've just published 0.12.1 for this.  Please try it out, and let me know if you're still having problems.
