### ISSUE TITLE
Using producer from C++

### ISSUE THREAD

**Issue by zwass** [awslabs/amazon-kinesis-producer#40]
Is there any precedent for using this library directly from a C++ program? It seems like the code is fairly tied into being used through IPC rather than in-process. Would you recommend against using it in-process in a C++ application?

**Comment by zwass** [comment]
Additionally, do you expect the C++ API to change? I see that the current version of the producer library is 0.10.2, will there eventually be a 1.0 release with breaking changes at the C++ level?

**Comment by jquadrin** [comment]
There would have to be a C++ wrapper for this to work. The daemon runs as a child process to prevent it from blocking the main process while doing aggregation and various IO related tasks. The aws c++ SDK comes with a kinesis API, this is the same API that the daemon uses internally.

**Comment by zwass** [comment]
Thank you. We went with the C++ SDK months ago.
