### ISSUE TITLE
Kinesis API signatures should be recalculated when network is unavailable for > 5 minutes.

### ISSUE THREAD

**Issue by jhawksley** [awslabs/amazon-kinesis-producer#41]
Ref: AWS Support case 1643879051.

When the network cable is removed from a Java/KPL client which pushes one payload every minute, after more than 5 minutes, the initial payloads raise:

```
[2016-02-04 14:39:19.910029] [0x000070000028d000] [error] [retrier.cc:59] PutRecords failed:
 {"__type":"InvalidSignatureException","message":
 "Signature expired: 20160204T133419Z is now earlier than 20160204T133420Z (20160204T133920Z - 5 min.)"}
```

We believe the KPL is trying the same PUT without recalculating the signature information.  AWS Support are taking the view that this should be handled by the client (which is in fact the workaround) but I think it's a leaky abstraction - the KPL should do this, since signature handling is not the client's responsibility.  Another factor is that the record TTL is set to an hour - I wouldn't expect a failure callback until that hour had elapsed.

Revisions: 
- amazon-kinesis-producer 0.10.2
- aws-java-sdk-core 1.10.50

**Comment by kevincdeng** [comment]
Thanks for reporting this. We'll address it in a future release.

**Comment by pfifer** [comment]
This should no longer occur, the AWS C++ SDK should recalculate the signature for each request.

If this is still a problem please feel free to re-open.

Thanks.
