### ISSUE TITLE
Sending metrics to CloudWatch failed when metrics namespace contained a /

### ISSUE THREAD

**Issue by sigmaris** [awslabs/amazon-kinesis-producer#42]
I set the metrics namespace to "FD/EventCollector" and added an additional metric dimension named "Environment". With this configuration I kept getting this error message from the KPL:

```
[2016-02-09 03:53:35.034485] [0x00007f18e54d3740] [error] [metrics_manager.cc:190] Metrics upload failed:
<ErrorResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/doc/2010-08-01/
Action=PutMetricData&amp;MetricData.member.1.Dimensions.member.1.Name=Environment&amp;MetricData.member.1.Dimensions.member.1.Value=...
```

I removed the / from the namespace and the problem stopped happening.

Operating system:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
$ uname -a
Linux dbvhostweb 3.2.0-97-virtual #137-Ubuntu SMP Thu Dec 17 18:38:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kevincdeng** [comment]
Thanks for reporting the bug. We will address this in the next release.

**Comment by pfifer** [comment]
This should be an issue with the 0.12.x release, since they now use the AWS C++ SDK.  Please re-open this if it's still an issue.

Thanks

**Comment by domenkosir** [comment]
I'm getting the same error using v0.10.1 (we can't upgrade because of legacy issues). Is this bug fixed in newer versions?

**Comment by domenkosir** [comment]
@sigmaris I managed to fix this by URL-decoding the metrics namespace.
`kinesisProducerConfiguration.setMetricsNamespace(urlDecode("foo/bar"))`
