### ISSUE TITLE
Java Process does not restart Daemon after crash

### ISSUE THREAD

**Issue by rdifalco** [awslabs/amazon-kinesis-producer#51]
If the C++ child process dies the Java process does nothing to restart it. Weird. So there appears to be no recovery options. For other's having this problem the best thing I can suggest is catching the Daemon Exception and then exiting the Java process so that something can restart it. But it appears you are pretty much dead in the water. 

My hope is that the KPL team will have the Java process restart the child process when it crashes (so the java process does not have to be restarted).

**Comment by pfifer** [comment]
The new version of the KPL should now restart the native process after a crash.  If you run across this again please let us know so we can investigate.

Thanks

**Comment by pc-jlai** [comment]
hi @pfifer 

do you know the exact version where this fix is included for the first time? We are running 1.11.0 and we are seeing "The child process has been shutdown and can no longer accept messages" issues. I am wondering if this is the same thing. 

Thank you.

**Comment by pfifer** [comment]
@pc-jlai The version number you posted is likely that of the AWS SDK for Java.   The KPL version number would be something like 0.10.X or 0.12.X.
