### ISSUE TITLE
0.15.10 is still not on maven repos like maven central

### ISSUE THREAD

**Issue by svenwilliger** [awslabs/amazon-kinesis-producer#559]
0.15.10 was released on Jan 4th and is still not found on any maven repos like maven central https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-producer

Please upload it, so that we can update from 0.15.8 since we cant because of the segfault in 0.15.9

**Comment by etspaceman** [comment]
Hey there - 

Any updates on this?

**Comment by ngsharsha** [comment]
Hello,

Is there any ETA for this to be released to maven central ?

**Comment by kjorg50** [comment]
Hello AWS team, any updates on this? We are waiting on this version to resolve some CVE's in the transitive dependencies. Thanks

**Comment by elrob** [comment]
I spoke to AWS support regarding this and was just informed that 0.15.10 has been made available:
https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-producer/0.15.10
