### ISSUE TITLE
Native binary output not routed into SLF4J

### ISSUE THREAD

**Issue by vdenisov** [awslabs/amazon-kinesis-producer#58]
Right now, any messages printed by the native binary (including error messages) are sent directly to the console - so they're lost if console output is unavailable (for example, when running via Boxfuse with logs sent to Graylog, as we happen to do). The proper solution would be to read stdout/stderr of the native process and output each line as a log message.

**Comment by pfifer** [comment]
This should be fixed with the new release of the KPL.  It should output the log from the [LogInputStreamReader](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/LogInputStreamReader.java).

**Comment by pfifer** [comment]
Please let us know if you are still having logging issues.

Thanks
