### ISSUE TITLE
Support Pod Identity compatible SDK

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [awslabs/amazon-kinesis-producer#591]
https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

It seems that both Java and CPP SDK should be upgraded

**Comment by piotrwielgolaski-tomtom** [comment]
Java SDK
https://github.com/awslabs/amazon-kinesis-producer/pull/588

**Comment by piotrwielgolaski-tomtom** [comment]
@chenylee-aws @lucienlu-aws could you take a look at this one?

**Comment by lucienlu-aws** [comment]
Merged #588

**Comment by piotrwielgolaski-tomtom** [comment]
@lucienlu-aws there is CPP SDK to update https://github.com/awslabs/amazon-kinesis-producer/blob/master/bootstrap.sh#L21
