### ISSUE TITLE
KPL sends invalid HTTP requests to EC2 metadata service

### ISSUE THREAD

**Issue by tazjin** [awslabs/amazon-kinesis-producer#61]
Hello,

we've been trying to get the KPL to run using IAM roles and instance profiles instead of hardcoding a key pair. Whenever we try to run this we get the following errors:

```
[2016-08-29 08:52:50.816171] [0x00007f4f66f4d700] [error] [io_service_socket.h:229] Error during socket read: End of file; 0 bytes read so far (169.254.169.254:80)
[2016-08-29 08:52:50.917202] [0x00007f4f66f4d700] [error] [io_service_socket.h:229] Error during socket read: End of file; 0 bytes read so far (169.254.169.254:80)
[2016-08-29 08:52:51.058269] [0x00007f4f6884f740] [error] [main.cc:156] Could not retrieve credentials from anywhere.
```

This seems very strange because using `wget` from the place where the KPL is running to get credentials from the metadata server works fine. Therefore I cranked out `tcpdump` to figure out what's going on.

Example of the data stream of a working wget-request:

```
GET /latest/meta-data/iam/security-credentials/flink-worker HTTP/1.1
User-Agent: Wget/1.16 (linux-gnu)
Accept: */*
Host: 169.254.169.254
Connection: Keep-Alive

HTTP/1.1 200 OK
Server: EC2ws
Date: Mon, 29 Aug 2016 08:52:33 GMT
Content-Length: 551
Content-Type: text/plain; charset=utf-8

{"Code":"Success","LastUpdated":"2016-08-29T08:41:55Z","Type":"AWS-HMAC","AccessKeyId":"REDACTED","SecretAccessKey":"REDACTED","Token":"REDACTED"}
```

(Note that the KPL has to first do a call to retrieve the role name, which we already included).

Now for the fun part. Example of a request sent by the KPL:

```
GET /latest/meta-data/iam/security-credentials/ HTTP/1.1

HTTP/1.1 400 Bad Request
Content-Type: text/plain
Connection: close

400 Bad Request: missing required Host header
```

It seems to be sending invalid HTTP requests (the Host header is [required](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html)). This seemed very strange to us because surely somebody must have run this code against the EC2 metadata server?

We took a look at the C++ source and ended up with this in the HTTP client code:

``` cpp
// http_request.cc
std::string HttpRequest::to_string() {
  generate_preamble();
  return preamble_ + data_;
}

void HttpRequest::generate_preamble() {
  std::stringstream ss;
  ss << method_ << " "
     << path_ << " "
     << http_version_
     << "\r\n";
  for (const auto& h : headers_) {
    ss << h.first << ":" << h.second << "\r\n";
  }
  ss << "\r\n";
  preamble_ = std::move(ss.str());
}
```

The `Host` header must be added manually while building up the request. However this never actually happens for the EC2 metadata calls, only for Kinesis itself and some metrics service:

```
~/s/amazon-kinesis-producer> ag -Q 'req.add_header("Host"'
aws/http/http.cc
57:  req.add_header("Host", "kinesis." + region + ".amazonaws.com");

aws/metrics/metrics_manager.cc
158:  req.add_header("Host", endpoint_);
```

This seems like a bug and should probably be addressed.

**Comment by drewsonne** [comment]
+1

**Comment by pfifer** [comment]
The new version of the KPL is using the AWS C++ SDK now, which should access the EC2 Metadata service correctly.  Unfortunately right now the KPL doesn't use the SDK credential classes, and instead relies on the credentials being passed in from the Java application.

This is somewhat of a regression from the previous version that sort of supported the existing credential types.  Adding support for credentials back should be relatively straight forward.

**Comment by tazjin** [comment]
@pfifer Hmm, does that mean instance profile sourced credentials basically can't be used now? Retrieving them manually in Java will yield credentials that expire quickly.

**Comment by pfifer** [comment]
The Java side of the KPL periodically retrieves the credentials, and sends them to the native components.  It's not quite as nice as using the AWS C++ SDK specific classes.  The default refresh rate is every 5 seconds.

**Comment by pfifer** [comment]
I'm going to close this, please feel free to re-open if you have additional questions.

Thanks
