### ISSUE TITLE
No implementation of get_sesssion_token for EnvVarAwsCredentialsProvider

### ISSUE THREAD

**Issue by ge1st** [awslabs/amazon-kinesis-producer#7]
Hi everyone,

It looks like there is no implementation of `get_session_token` for any credential provider other than `InstanceProfileAwsCredentialsProvider` (https://github.com/awslabs/amazon-kinesis-producer/blob/162a68a8d91f3a8060416635ae8f9f45613aa805/aws/auth/credentials.h#L102). 

This would be really helpful to have for at least `EnvVarAwsCredentialsProvider` since I use session tokens for local development and it would also allow for the KPL to be used in Lambda since the credentials are passed there via environment variables.

I'd love to do a PR but I can't seem to build on my machine. Curl seems to become unhappy on my Arch laptop, but that's another issue.

```
curl: symbol lookup error: /usr/lib/libssh2.so.1: undefined symbol: EVP_cast5_cbc
```

thanks

**Comment by kevincdeng** [comment]
Hi ge1st,

Are you using Java? The next release moves credentials retrieval up into the wrapper layer, such that the AWS SDK credentials providers can be used. If you're using the wrapper this use case will be automatically addressed by DefaultAWSCredentialsProviderChain (which is the default).

The release will be available very soon.

**Comment by ge1st** [comment]
I am using Java; and that would be excellent! I hope very soon is meant to mean a few days. Thanks, I'll close the pull request.

**Comment by kevincdeng** [comment]
Hi ge1st,

The 0.10.0 release is now available. See the [sample code](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducer.java#L131) for a quick example of how to configure credentials.

**Comment by ge1st** [comment]
Yep that let me use tokens! Thanks for help.
