### ISSUE TITLE
Adjust Warning on SIGPIPE to be Less Severe

### ISSUE THREAD

**Issue by pfifer** [awslabs/amazon-kinesis-producer#71]
As part of the change to the AWS C++ SDK there is the possibility of seeing some additional messages related to connection issues between the host, and Kinesis.  This occurs due to OpenSSL triggering a PIPE signal when a connection error occurs.  Normally curl handles the PIPE signal when creating the connection using OpenSSL, but there is currently a problem enabling the signal handler.

For the short term we will tone down the warning for PIPE signals, and add a clearer warning.

If you see this error often it could indicate issues affecting the connection to between your host, and Kinesis.

**Comment by jmmirick** [comment]
Could you confirm that this is related to [an issue](https://forums.aws.amazon.com/thread.jspa?messageID=749181&#749181) I posted in the Kinesis forum? Thank you.

**Comment by pfifer** [comment]
I've just responded to your issue on the forums, and the stack trace is related to this issue.  You can tell if the stack trace includes SSL, or BIO functions.

**Comment by pfifer** [comment]
Fix for this is in PR #77

**Comment by pfifer** [comment]
[Release v0.12.2 of the KPL](https://github.com/awslabs/amazon-kinesis-producer/releases/tag/v0.12.2) fixes this.

**Comment by jmmirick** [comment]
We downloaded the new release Friday and saw that it was fixed. Thanks very much!
