### ISSUE TITLE
KinesisProducer.extractBinaries exception on Win64

### ISSUE THREAD

**Issue by ramtg** [awslabs/amazon-kinesis-producer#73]
Can someone please offer a suggestion on how to work around the following exception that KinesisProducer.extractBinaries() throws when trying to copy the native binary to c:\Users\..\AppData\Local\Temp .

This issue is happening  on Win64 with 0.12.x .

- java.lang.RuntimeException: Could not copy native binaries to temp directory C:\Users\...\AppData\Local\Temp\amazon-kinesis-producer-native-binaries
- 	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:844)
- 	at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:242)
- ...
- 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
- 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
- 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
- 	at java.lang.reflect.Method.invoke(Method.java:498)
- 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
- Caused by: java.lang.NullPointerException
- 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
- 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
- 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
- 	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
- 	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:803)
- 	... 12 more
-

**Comment by pfifer** [comment]
Unfortunately for the 0.12.x releases we've had to temporarily remove Windows support.  We're are looking into adding Windows support back, but I don't have an ETA at this time.

**Comment by davidhroberts1** [comment]
Hi, 

Has there been any updates here?  Running into the same problem.

**Comment by ramtg** [comment]
@davidhroberts1 
Tried KPL 0.12.3  ;  Continuing to have the issue on Windows .

**Comment by ravi2274** [comment]
Same issue as @ramtg! 
Build the project with version 0.10.2, worked like a charm.
Any timelines on support of Windows x64 for the newer version?

**Comment by etspaceman** [comment]
+1

**Comment by asumawang** [comment]
+1

**Comment by harryho** [comment]
Same issue.   :-(

**Comment by zodeus** [comment]
Same issue here

**Comment by psiedlinski** [comment]
+1
any progress?

**Comment by gabrek7** [comment]
Same issue here =(

**Comment by moranabelev** [comment]
+1
@pfifer - any updates?

**Comment by sangeetasan10** [comment]
+1
same issue.

**Comment by kennyk65** [comment]
Same issue.  Windows 10.  Java SDK 1.11.205, kinesis-producer-library 0.12.5.

**Comment by benMain** [comment]
Are there any temporary workarounds other than rolling back the version of KPL?

**Comment by denystyshetskyy** [comment]
Same Issue here +1

**Comment by nabi-rd** [comment]
+1 with version 0.12.5

**Comment by ErrorMonkeys** [comment]
+1

**Comment by pfifer** [comment]
Windows support is coming soon.

**Comment by ramtg** [comment]
Thank you!!!
