### ISSUE TITLE
Broken pipe error after upgrading to KPL 0.12.1

### ISSUE THREAD

**Issue by lliu-mm** [awslabs/amazon-kinesis-producer#75]
Our application is running on aws (m3.large). We recently upgraded the KPL to 0.12.1 and saw the following error.

2016-11-07 21:33:52.659 ERROR [kpl-daemon-0003] [ERROR]
---BEGIN ERROR----
Signal: SIGPIPE
Description: Broken pipe
---BEGIN STACK TRACE---
4656540 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/aws/utils/backtrace/gcc_backtrace.cc:104 _ZN3aws5utils9backtrace22stack_trace_for_signalEib(...)
4655134 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/aws/utils/signal_handler.cc:84 signal_handler(...)
140183287722143 140183287722143??:0 ??
140183287718301 140183287718301 write:0 ??
7101725 7101725 sock_write:0 ??
7093771 7093771 BIO_write:0 ??
6739233 6739233 ssl3_write_pending:0 ??
6748769 6748769 ssl3_dispatch_alert:0 ??
6730417 6730417 ssl3_shutdown:0 ??
6632883 6632883 Curl_ossl_close:0 ??
6500030 6500030 Curl_disconnect:0 ??
6500211 6500211 disconnect_if_dead:0 ??
6500264 6500264 call_disconnect_if_dead:0 ??
6435089 6435089 Curl_conncache_foreach:0 ??
6511269 6511269 Curl_connect:0 ??
6421954 6421954 multi_runsingle:0 ??
6424412 6424412 curl_multi_perform:0 ??
6404442 6404442 curl_easy_perform:0 ??
5559808 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/third_party/aws-sdk-cpp/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:407 _ZNK3Aws4Http14CurlHttpClient11MakeRequestERNS0_11HttpRequestEPNS_5Utils10RateLimits20RateLimiterInterfaceES7_(...)
6341697 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/third_party/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:203 _ZNK3Aws6Client9AWSClient17AttemptOneRequestERKSsRKNS_23AmazonWebServiceRequestENS_4Http10HttpMethodE(...)
6342561 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/third_party/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:130 _ZNK3Aws6Client9AWSClient19AttemptExhaustivelyERKSsRKNS_23AmazonWebServiceRequestENS_4Http10HttpMethodE(...)
6349102 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/third_party/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:365 _ZNK3Aws6Client13AWSJsonClient11MakeRequestERKSsRKNS_23AmazonWebServiceRequestENS_4Http10HttpMethodE(...)
5771987 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/third_party/aws-sdk-cpp/aws-cpp-sdk-kinesis/source/KinesisClient.cpp:550 _ZNK3Aws7Kinesis13KinesisClient10PutRecordsERKNS0_5Model17PutRecordsRequestE(...)
5750942 /home/pfifer/producer-gh/amazon-kinesis-producer-gh/third_party/aws-sdk-cpp/aws-cpp-sdk-kinesis/source/KinesisClient.cpp:573 _ZNK3Aws7Kinesis13KinesisClient21PutRecordsAsyncHelperERKNS0_5Model17PutRecordsRequestERKSt8functionIFvPKS1_S5_RKNS_5Utils7OutcomeINS2_16PutRecordsResultENS_6Client8AWSErrorINS0_13KinesisErrorsEEEEERKSt10shared_ptrIKNSC_18AsyncCallerContextEEEESO_(...)
8292111 ../../../../../gcc-4.9.3/libstdc++-v3/src/c++11/thread.cc:84 execute_native_thread_routine(...)
140183287688015 140183287688015 start_thread:0 ??
140183273666908 140183273666908 clone:0 ??
---END STACK TRACE---
---END ERROR--- [] com.amazonaws.services.kinesis.producer.LogInputStreamReader

Try to debug the issue. The "/home/pfifer/" directory seems not exist. 
admin@:~$ls /home/pfifer/producer-gh/amazon-kinesis-producer-gh/aws/utils/
ls: cannot access /home/pfifer/producer-gh/amazon-kinesis-producer-gh/aws/utils/: No such file or directory

**Comment by pfifer** [comment]
This isn't actually an error, but occurs when the connection between the host and Kinesis is interrupted.  I'm currently planning to prevent this stack trace from appearing when a failure occurs, but I don't have an ETA on that at this time.

The paths in the stack trace are from the original build of the C++ components that occured on my build host, and wouldn't be present on your system.  

More information about this can be found in Issue #71
