### ISSUE TITLE
Disabling TLS for local integration tests

### ISSUE THREAD

**Issue by NicolasFrd** [awslabs/amazon-kinesis-producer#88]
Hello,

I'm working on an application using the KPL and the KCL. I would like to write some integration tests that do not rely on AWS, but instead use a Kinesis implementation running locally (Kinesalite).

Since the KPL only supports TLS, I have to start Kinesalite with SSL enabled and disable the certificate verification in the KPL configuration. However, since the KCL does not provide a similar option, it fails when trying to validate the certificate. I also have an issue for the same reason when trying to use the AmazonKinesisClient for creating a Stream before the tests begins.

I found a Kinesalite issue from someone facing the same problem: https://github.com/mhart/kinesalite/issues/16. A tricky workaround is presented, however it involves changes on the system itself i.e. aliasing an host in /etc/hosts, which is not doable in my situation. It is also unclean, as I would like my tests to run on any system.

My question would be: is it planned to support disabling TLS?

Thanks a lot! I look forward to reading from you.

**Comment by pfifer** [comment]
Kinesis only support communications over TLS, so it's unlikely we will disable TLS.  What you can do is use a self signed cert and have the KCL Java process use that self signed cert in it's trust store.  

You can override the certificate store that java uses via 
```
-Djavax.net.ssl.trustStore=certs/TrustStoreName.jks -Djavax.net.ssl.trustStorePassword=TrustStorePassword
```
All you need to do is create a keystore file with your self signed certs.  If you want to access TLS services other than your own test proxy, you will need to add the existing certs the JRE's cert store.

**Comment by NicolasFrd** [comment]
Hi,

thanks a lot for the quick answer and the explanation. I'll give it a try.

**Comment by GDP-Ariza** [comment]
Hi,

I was able to make a self-signed certificate using the following command 

`keytool -genkey -keyalg RSA -alias tomcat -keystore selfsigned.jks -validity 3 -keysize 2048`

from https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2004193

and have these command before my program (I put the certificate in `~/`)
```
        System.setProperty("javax.net.ssl.trustStore", "~/selfsigned.csr");
        System.setProperty("javax.net.ssl.trustStorePassword", "myPassword");
```

However, I got this result:
```
Unable to execute HTTP request: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

And this is my declaration for KCL
```
        KinesisClientLibConfiguration config = new KinesisClientLibConfiguration(
                "kinesis-app", MY_STREAM, new DefaultAWSCredentialsProviderChain(), "worker-1")
                .withKinesisEndpoint("https://localhost:4567")
                .withInitialPositionInStream(InitialPositionInStream.TRIM_HORIZON);
```

Any idea about why it might happen?

Thanks
