### ISSUE TITLE
Is this thing configurable?

### ISSUE THREAD

**Issue by rokka-n** [awslabs/amazon-kinesis-producer#89]
java -jar ~/Downloads/KinesisProducer.jar
0 seconds, 0 records total, 0.00 RPS (avg last 10s)
1 seconds, 0 records total, 0.00 RPS (avg last 10s)
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream spark-demo under account xxxxxxxx not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: xxx)

**Comment by pfifer** [comment]
The Kinesis Producer is a library intended for integration into your program.  If you're looking just to publish data to Kinesis you might want to investigate the [Kinesis Agent](https://github.com/awslabs/amazon-kinesis-agent). 

Feel free to re-open if you have any other questions.
